/* Spanish (es-sp) resource file */

var oResources={
  /* Categories - categorias.ehc */
  "cat-more-popular":"Más Populares",
  "cat-more-brand-a-to-z":"Nombre de la A a la Z",
  "cat-more-brand-z-to-a":"Nombre de la Z a la A",
  "cat-more-random":"Aleatorio",

  /* Header */
  "header-cat-home":"Home",
  "header-cat-sales":"Promociones",
  "header-cat-releases":"Lanzamientos",
  "header-cat-cart":"Carrito",
  "header-cat-my-orders":"Mis pedidos",
  "header-cat-my-shopping-list":"Lista de la Compra",
  "header-cat-my-wishlist":"Lista de Deseos",
  "header-cat-register":"Registro",
  "header-cat-newsletter":"Informativo",
  "header-cat-contact-us":"Contáctenos",
  "header-autosuggest-input":"Busca productos",
  "header-cat-menu-close":"Cerrar",  
  "header-mainbar-container-search-icon":"Buscar",    
  "header-cat-search-close":"Cerrar",   
  "header-voice-search-mglass":"Buscar",
  
  /* Home */
  "home-title-sales":"Productos en Promoción",
  "home-title-special-offers":"Productos con OFERTAS ESPECIALES!",
  "home-title-special-offers-text":"Los mejores productos con los mejores descuentos!",
  "home-title-special-offers-buy-now":"COMPRE AHORA",
  "home-title-last-releases":"Últimos Lanzamientos",
  "home-title-last-awesome-releases":"¡Lanzamientos INCREÍBLES!",
  "home-title-last-awesome-releases-text":"¡Las últimas novedades! ¡Productos con los mejores precios!",
  "home-title-last-awesome-releases-buy-now":"COMPRE AHORA",
  "home-title-featured-products":"Productos Destacados",
  "home-section-payment":"Vea nuestros medios de Pago",
  "home-section-security":"Vea nuestras insignias de seguridad",
  "home-section-delivery":"Conozca nuestra entrega con Envío Rápido",
  "home-section-contact-us":"¿Alguna duda? Hable con nosotros",  
  "price-in-cash":"a la vista",     
  "home-banner-slideshow-sales":"Productos en Promoción",  
  "home-banner-slideshow-releases":"Últimos Lanzamientos",
  "home-banner-1-slideshow-title":"¡Increíbles ofertas!",
  "home-banner-1-slideshow-subtitle":"¡Productos con los mejores descuentos!", 
  "home-banner-1-slideshow-button":"COMPRE AHORA",  
  "home-banner-2-slideshow-title":"¡Lanzamientos imperdibles!",
  "home-banner-2-slideshow-subtitle":"¡Productos con los mejores precios!",    
  "home-banner-2-slideshow-button":"COMPRE AHORA", 

  /* Featured Products */
  "featured-products-title":"Productos Destacados",

  /* Footer */
  "footer-section-title-product":"Productos",
  "footer-section-title-home":"Home",
  "footer-section-title-sales":"Promociones",
  "footer-section-title-releases":"Lanzamientos",
  "footer-section-title-highlights":"Destacados",
  "footer-section-title-search":"Búsqueda detallada",  
  "footer-section-title-my-account":"Mi cuenta",
  "footer-section-title-shopping-cart":"Carrito de compras",
  "footer-section-title-my-orders":"Mis pedidos",
  "footer-section-title-register":"Registro",
  "footer-section-title-login":"Login",
  "footer-section-title-recommend-us":"Recomiéndenos",
  "footer-section-title-newsletter":"Informativo",
  "footer-section-title-information":"Información",
  "footer-section-title-help-center":"Centro de ayuda",
  "footer-section-title-news":"Noticias",
  "footer-section-title-delivery":"Entrega",
  "footer-section-title-security":"Seguridad",
  "footer-section-title-contact-us":"Contáctenos",
  "footer-section-newsletter-text":"¡Regístrese para recibir ofertas y descuentos!",
  "footer-section-newsletter-text-input":"Suscribite con tu email",
  "footer-section-title-payment":"Pago",
  "footer-section-powered-by":"Comercio electrónico impulsado por <strong>ehcommerce</strong>",
  "footer-cnpj":" ",
  "footer-newsletter-submit-button":"Suscribite Newsletter",

  /* Footer - History */
  "footer-history-title":"Mi historial de navegación",

  /* Product List */
  "list-filters-title":"Filtros",
  "list-price-no-interest":"sin interés",
  "list-price-was":"De",
  "list-price-now":"Por",
  "list-price-call-us":"CONTACTO",  
  "list-filters-close":"Cerrar", 
  "topic-query-product-cod":"sujeto=Consulta%20en%20producto%20(Código%20",
  "list-sold-out":"Producto no disponible",

  /* Product List - Sort by */
  "list-sort-by-title":"Ordenar por:",
  "list-sort-by-title-select":"Seleccionar",
  "list-sort-by-title-default":"Estándar",
  "list-sort-by-title-releases":"Lanzamientos",
  "list-sort-by-title-highlights":"Destacados",
  "list-sort-by-title-cat-names":"Nombres de las categorías",
  "list-sort-by-title-product-names":"Nombres de los productos",
  "list-sort-by-title-reviews":"Evaluaciones de los clientes",
  "list-sort-by-title-price-low":"Precio de menor a mayor",
  "list-sort-by-title-price-high":"Precio de mayor a menor",

  /* Product Details */
  "details-departments-title":"Categoría:",
  "details-description-title":"Descripción",
  "details-reviews-title":"Calificación",
  "details-zip-code-title":"Ver el valor de envío",
  "details-zip-code-qty":"Ctd.",
  "details-zip-code-simulation-brazil":"Simulación solo para brasil",
  "details-buy-together-checkbox":"Seleccione",
  "details-buy-together-title":"Comprar juntos",
  "details-buy-together-add-to-cart-button":"Añadir a la Cesta",
  "details-buy-together-price":"Precio",
  "details-buy-together-price-was":"de",
  "details-buy-together-price-now":"Por",
  "details-buy-together-save":"Contado",
  "details-price-no-interest":"Sin interés",
  "details-price-no-interest-in":"de",
  "details-price-save":"Contado",
  "details-add-to-wishlist-off":"Añadir a la lista de deseos",
  "details-add-to-wishlist-on":"Añadido en la lista de deseos",

  /* Shopping List */
  "shopping-list-title":"Mi lista de compra",
  "shopping-list-one-product-line":"Inserte un producto por línea.",
  "shopping-list-quick-instructions":"Instrucciones rápidas:",
  "shopping-list-enter-one-product-line":"Escriba un producto por línea",
  "shopping-list-press-enter-text":"Pulse <span class='strColor'>ENTER</span> después de introducir cada producto. Si lo prefiere, pegue una lista de productos con un producto por línea.",
  "shopping-list-find-products":"Encuentre los productos",
  "shopping-list-after-typing-all-products":"Después de escribir todos los productos de la lista, haga clic en el botón <span class='strColor'> BUSCAR PRODUCTOS </span>.",
  "shopping-list-check-results":"Compruebe los resultados",
  "shopping-list-besides-each-product":"Al lado de cada producto, usted tendrá las opciones:",
  "shopping-list-search-products":"Buscar producto",
  "shopping-list-mark-purchased":"Marcar como comprado",
  "shopping-list-delete-list":"Borrar de la lista",
  "shopping-list-add-cart":"Añadir a la cesta",
  "shopping-list-click-each-item-desired-product":"Haga clic en cada elemento de la lista y seleccione el producto que desee. Después de hacer clic en <span class='strColor'> COMPRAR </span>.",
  "shopping-list-change-list":"Cambiar lista",
  "shopping-list-restart":"Empezar de nuevo",

  /* Product not find */
  "product-not-find-title":"No se encontraron productos para esta búsqueda.",
  "product-not-find-tips-search":"Consejos para su búsqueda:",
  "product-not-find-check-errors":"- Compruebe si hay errores de escritura",
  "product-not-find-single-word":"- Intente utilizar una sola palabra",
  "product-not-find-desired-term":"- Busque utilizar sinónimos al término deseado",
  "product-not-find-click-here":"Haga clic aquí",
  "product-not-find-click-here-text":"y haga una nueva búsqueda.",
  "product-not-find-click-here-sales-btn":"promociones",

  /* Error 404 */
  "error-404-title":"Error 404",
  "error-404-text":"Lo siento, página no encontrada.",

  /* Cart */
  "cart-zip-code-title":"Introduzca el código postal para calcular el envío",
  "cart-zip-code-button":"Calcular Envío",
  "cart-enter-coupon-button":"Aplicar Cupón",
  "cart-zip-code-to-calculate":"a calcular",
  "cart-zip-code-shipping-title":"Envío",

  /* Checkout */
  "checkout-steps-identification":"Identificación",
  "checkout-steps-payment":"Pago",
  "checkout-steps-confirmation":"Confirmación",
  "checkout-enter-coupon-title":"Ingresa el código (opcional)",
  "checkout-enter-coupon-button":"Aplicar Cupón",
  "checkout-enter-invalid-coupon":"Cupón inválido",
  "checkout-enter-discount-coupon-text":"¿Le gustaría ingresar el código para un cupón de descuento?",
  "checkout-enter-discount-coupon-redirected-text":"Si usted tiene un cupón de descuento usted será redirigido a la página donde puede insertar este cupón para obtener el descuento.",
  "checkout-steps-payment-title":"Pago",
  "checkout-steps-payment-text":"Las opciones de pago se mostrará después del paso de la elección del flete.",

  /* Order Confirmation */
  "order-confirmation-payment":"Forma de pago",
  "order-confirmation-payment-data":"Datos de pago",
  "order-confirmation-payment-information":"Información de su solicitud:",

  /* Side Cart */
  "side-cart-shopping-cart-title":"CESTA",
  "side-cart-shopping-item":"item",
  "side-cart-shopping-items":"itens",
  "side-cart-shopping-empty":"Su cesta está vacía",
  "side-cart-shopping-zip-code":"Código Postal",
  "side-cart-shopping-zip-code-to-calculate":"a calcular",
  "side-cart-shopping-zip-code-invalid":"No válido",
  "side-cart-shopping-zip-code-button":"Calcular",
  "side-cart-shopping-zip-code-total-pay":"Total a pagar",
  "side-cart-shopping-gift":"Embalaje para regalo",
  "side-cart-shopping-total-itens":"Total de itens",
  "side-cart-shopping-proceed-checkout":"IR PARA EL PAGO",
  "side-cart-shopping-listing-20":"Listando los &nbsp;<b>primeros 20</b>&nbsp;productos de la&nbsp;",
  "side-cart-shopping-listing-20-cart":"cesta",
  "side-cart-shopping-enter-coupon-button":"Aplicar cupón",  
  "side-cart-shopping-discount":"Descuentos",    
  "side-cart-shopping-interest-10x":"En hasta 10x de", 

  /* Smart Suggestions */
  "smart-suggestions-search":"Búsqueda",  
  "smart-suggestions-suggested":"sugerido",   
  "smart-suggestions-for-google":"por Google", 

  /* Miscellaneous */
  "form-submit-search-correctly":"Rellena la búsqueda correctamente",  
  "button-cart-warn-me":"Notificarme",  
  "button-cart-warn-me-when-available":"cuando esté disponible.", 
  "show-for-cash-payments-text":"Para los pagos a la vista gane", 
  "show-for-cash-payments-discount-text":"% de descuento",
  "show-discount-price":"Valor con descuento",
  "notify-when-available":"Avisar cuando esté disponible",  
  "cart-on-page-go-to-shopping-cart":"Ir para la cesta",   
  "get-shipping-insert-zip-code":"Insertar código postal", 
  "get-shipping-insert-zip-code-free-shipping":"ENVÍO GRATIS", 
  "process-xml-cep-shipping":"Envío:", 
  "product-has-been-removed-from-cart":"El producto se ha eliminado del carro porque ya no tenemos en stock", 
  "quantity-changed-quantity-stock":"La cantidad se ha cambiado a la cantidad máxima en stock disponible en ese momento:", 
  "unfortunately-not-have":"Desafortunadamente no tenemos", 
  "unfortunately-not-have-units-stock":"unidades en stock",     
  "change-qty-product-removed":"Producto eliminado",  
  "change-qty-amount-changed":"Cantidad modificada", 
  "change-qty-cart-product-removed":"Producto eliminado",

  /* Buy Together */
  "details-buy-together-price":"Precio",
  "details-buy-together-price-was":"de",
  "details-buy-together-price-now":"Por",
  "details-buy-together-save":"Contado",

  /* Grid */
  "grid-text-select-options-below":"Seleccione las opciones",
  "grid-add-to-cart-button":"Añadir a la Cesta",
  "grid-ready-button":"¡Añadiendo!", 
  "grid-contact-us-button":"Contáctenos",   
  "grid-sold-out-button":"Agotado",    
  "grid-choose-options-above-button":"Elija las opciones",   
  "grid-select-text":"Selecciona",
  "grid-select-options-wishlist":"Seleccione las opciones anteriores para insertar en la lista de deseos.",
  "grid-select-payments-win":"Para los pagos a la vista gane",
  "grid-select-payments-win-discount":"% de descuento",
  "grid-select-payments-win-discount-value":"Valor con descuento",
  "grid-select-price-on-request":"Precio bajo consulta",
  "grid-select-products-missing-descriptors":"Hay uno o más productos con descriptores ausentes!",
  "grid-quantity-stock":"Cantidad en inventario",
  "grid-quantity-requested-equal-greater":"La cantidad solicitada debe ser igual o superior a 1.",
  "grid-stock-higher-available":"Inventario solicitado más alto que el disponible.",
  "grid-stock-available-now":"Inventario disponible actualmente", 
  "grid-select-available-product":"Seleccione un producto disponible primero.",
  "grid-select-product-first":"Seleccione primero las opciones del producto",

  /* Calculate Shopping cart */ 
  "cart-update-text":"Actualizar",
  "cart-zip-code":"Calcular Envío",

  /* Autosuggest */
  "auto-suggest-suggested-searches":"Búsqueda avanzada"

}