/* Portugal Portugues (pt-pt) resource file */

var oResources={
  /* Categories - categorias.ehc */
  "cat-more-popular":"Mais Populares",
  "cat-more-brand-a-to-z":"Ordem Alfabética A-Z",
  "cat-more-brand-z-to-a":"Ordem Alfabética A-Z",
  "cat-more-random":"Aleatório",

  /* Header */
  "header-cat-home":"Home",
  "header-cat-sales":"Promoções",
  "header-cat-releases":"Lançamentos",
  "header-cat-cart":"Carrinho",
  "header-cat-my-orders":"Meus pedidos",
  "header-cat-my-shopping-list":"Lista de Compra",
  "header-cat-my-wishlist":"Lista de Desejos",
  "header-cat-register":"Cadastro",
  "header-cat-newsletter":"Newsletter",
  "header-cat-contact-us":"Contato",
  "header-autosuggest-input":"Digite sua busca aqui",
  "header-cat-menu-close":"Fechar",  
  "header-mainbar-container-search-icon":"Buscar",    
  "header-cat-search-close":"Fechar",   
  "header-voice-search-mglass":"Buscar",
  
  /* Home */
  "home-title-sales":"Produtos em Promoção",
  "home-title-special-offers":"Produtos com Promoções IMPERDÍVEIS!",
  "home-title-special-offers-text":"Os melhores produtos com os melhores descontos!",
  "home-title-special-offers-buy-now":"COMPRE AGORA",
  "home-title-last-releases":"Últimos Lançamentos",
  "home-title-last-awesome-releases":"Lançamentos INCRÍVEIS!",
  "home-title-last-awesome-releases-text":"As últimas novidades! Produtos com os melhores preços!",
  "home-title-last-awesome-releases-buy-now":"COMPRE AGORA",
  "home-title-featured-products":"Produtos em Destaque",
  "home-section-payment":"Veja nossos meios de Pagamento",
  "home-section-security":"Veja nossos selos de Segurança",
  "home-section-delivery":"Conheça nossa entrega com Frete Rápido",
  "home-section-contact-us":"Alguma Dúvida? Fale Conosco",  
  "price-in-cash":"à vista",     
  "home-banner-slideshow-sales":"Produtos em Promoção",  
  "home-banner-slideshow-releases":"Últimos Lançamentos", 
  "home-banner-1-slideshow-title":"Ofertas Arrasadoras!",
  "home-banner-1-slideshow-subtitle":"Produtos com os melhores descontos!", 
  "home-banner-1-slideshow-button":"COMPRE AGORA",  
  "home-banner-2-slideshow-title":"Lançamentos Imperdíveis!",
  "home-banner-2-slideshow-subtitle":"Produtos com os melhores preços!",    
  "home-banner-2-slideshow-button":"COMPRE AGORA", 

  /* Featured Products */
  "featured-products-title":"Produtos em Destaques",

  /* Footer */
  "footer-section-title-product":"Produtos",
  "footer-section-title-home":"Home",
  "footer-section-title-sales":"Promoções",
  "footer-section-title-releases":"Lançamentos",
  "footer-section-title-highlights":"Destaques",
  "footer-section-title-search":"Busca detalhada",  
  "footer-section-title-my-account":"Minha conta",
  "footer-section-title-shopping-cart":"Carrinho de compras",
  "footer-section-title-my-orders":"Meus pedidos",
  "footer-section-title-register":"Cadastro",
  "footer-section-title-login":"Login",
  "footer-section-title-recommend-us":"Indique a loja",
  "footer-section-title-newsletter":"Newsletter",
  "footer-section-title-information":"Informações",
  "footer-section-title-help-center":"Central de ajuda",
  "footer-section-title-news":"Notícias",
  "footer-section-title-delivery":"Entrega",
  "footer-section-title-security":"Segurança",
  "footer-section-title-contact-us":"Fale connosco",
  "footer-section-newsletter-text":"Inscreva-se para receber ofertas e descontos!",
  "footer-section-newsletter-text-input":"Digite seu e-mail",
  "footer-section-title-payment":"Pagamento",
  "footer-section-powered-by":"Tecnologia de comércio eletrônico <strong>ehcommerce</strong>",
  "footer-cnpj":" ",
  "footer-newsletter-submit-button":"Enviar Newsletter",

  /* Footer - History */
  "footer-history-title":"Meu histórico de navegação",

  /* Product List */
  "list-filters-title":"Filtros",
  "list-price-no-interest":"sem juros",
  "list-price-was":"De",
  "list-price-now":"Por",
  "list-price-call-us":"CONSULTE-NOS",  
  "list-filters-close":"Fechar", 
  "topic-query-product-cod":"assunto=Consulta%20sobre%20produto%20(Código%20",  
  "list-sold-out":"Produto Indisponível", 

  /* Product List - Sort by */
  "list-sort-by-title":"Ordenar por:",
  "list-sort-by-title-select":"Selecione",
  "list-sort-by-title-default":"Padrão",
  "list-sort-by-title-releases":"Lançamentos",
  "list-sort-by-title-highlights":"Destaques",
  "list-sort-by-title-cat-names":"Nomes das categorias",
  "list-sort-by-title-product-names":"Nomes dos produtos",
  "list-sort-by-title-reviews":"Avaliações dos clientes",
  "list-sort-by-title-price-low":"Preços menores",
  "list-sort-by-title-price-high":"Preços maiores",

  /* Product Details */
  "details-departments-title":"Categoria:",
  "details-description-title":"Descrição",
  "details-reviews-title":"Avaliações",
  "details-zip-code-title":"Veja o valor do frete",
  "details-zip-code-qty":"Qtd.",
  "details-zip-code-simulation-brazil":"Simulação apenas para o Brasil",
  "details-buy-together-checkbox":"Comprar junto",
  "details-buy-together-title":"Compre junto",
  "details-buy-together-add-to-cart-button":"Comprar",
  "details-buy-together-price":"Preço",
  "details-buy-together-price-was":"de",
  "details-buy-together-price-now":"por",
  "details-buy-together-save":"Economize",
  "details-price-no-interest":"sem juros",
  "details-price-no-interest-in":"de",
  "details-price-save":"Economize",
  "details-add-to-wishlist-off":"Adicione na Lista de Desejos",
  "details-add-to-wishlist-on":"Adicionado na Lista de Desejos",

  /* Shopping List */
  "shopping-list-title":"Minha lista de compra",
  "shopping-list-one-product-line":"Insira um produto por linha.",
  "shopping-list-quick-instructions":"Instruções rápidas:",
  "shopping-list-enter-one-product-line":"Digite um produto por linha",
  "shopping-list-press-enter-text":"Tecle <span class='strColor'>ENTER</span> após digitar cada produto. Se preferir, cole uma lista de produtos com um produto por linha.",
  "shopping-list-find-products":"Encontre os produtos",
  "shopping-list-after-typing-all-products":"Após digitar todos os produtos da lista, clique no botão <span class='strColor'>BUSCAR PRODUTOS</span>.",
  "shopping-list-check-results":"Verifique os resultados",
  "shopping-list-besides-each-product":"Ao lado de cada produto, você terá as opções:",
  "shopping-list-search-products":"Buscar produto",
  "shopping-list-mark-purchased":"Marcar como comprado",
  "shopping-list-delete-list":"Apagar da lista",
  "shopping-list-add-cart":"Adicione ao carrinho",
  "shopping-list-click-each-item-desired-product":"Clique em cada item da lista e selecione o produto desejado. Depois é só clicar em <span class='strColor'>COMPRAR</span>.",
  "shopping-list-change-list":"Alterar lista",
  "shopping-list-restart":"Recomeçar",

  /* Product not find */
  "product-not-find-title":"Nenhum produto encontrado para esta busca.",
  "product-not-find-tips-search":"Dicas para a sua busca:",
  "product-not-find-check-errors":"- Verifique se há erros de digitação",
  "product-not-find-single-word":"- Tente utilizar uma única palavra",
  "product-not-find-desired-term":"- Procure utilizar sinônimos ao termo desejado",
  "product-not-find-click-here":"Clique aqui",
  "product-not-find-click-here-text":"para fazer uma nova busca.",
  "product-not-find-click-here-sales-btn":"promoções",

  /* Error 404 */
  "error-404-title":"Erro 404",
  "error-404-text":"Desculpe, página não encontrada.",

  /* Cart */
  "cart-zip-code-title":"Digite o CEP para calcular o frete",
  "cart-zip-code-button":"Calcular Frete",
  "cart-enter-coupon-button":"Aplicar cupom",
  "cart-zip-code-to-calculate":"a calcular",
  "cart-zip-code-shipping-title":"Frete",

  /* Checkout */
  "checkout-steps-identification":"Identificação",
  "checkout-steps-payment":"Pagamento",
  "checkout-steps-confirmation":"Confirmação",
  "checkout-enter-coupon-title":"Informe seu cupom (opcional)",
  "checkout-enter-coupon-button":"Aplicar cupom",
  "checkout-enter-invalid-coupon":"Cupom inválido",
  "checkout-enter-discount-coupon-text":"Deseja inserir o código de um cupom de desconto?",
  "checkout-enter-discount-coupon-redirected-text":"Caso tenha um cupom de desconto você será redirecionado para a página onde pode inserir este cupom para obter o desconto.",
  "checkout-steps-payment-title":"Pagamento",
  "checkout-steps-payment-text":"As opções de pagamento serão exibidas após a etapa da escolha do frete.",

  /* Order Confirmation */
  "order-confirmation-payment":"Forma de pagamento",
  "order-confirmation-payment-data":"Dados para pagamento",
  "order-confirmation-payment-information":"Informações do seu pedido:",

  /* Side Cart */
  "side-cart-shopping-cart-title":"CARRINHO",
  "side-cart-shopping-item":"item",
  "side-cart-shopping-items":"itens",
  "side-cart-shopping-empty":"Seu carrinho está vazio",
  "side-cart-shopping-zip-code":"CEP",
  "side-cart-shopping-zip-code-to-calculate":"a calcular",
  "side-cart-shopping-zip-code-invalid":"CEP inválido",
  "side-cart-shopping-zip-code-button":"Calcular",
  "side-cart-shopping-zip-code-total-pay":"Total a pagar",
  "side-cart-shopping-gift":"Embalagem para presente",
  "side-cart-shopping-total-itens":"Total dos itens",
  "side-cart-shopping-proceed-checkout":"IR PARA O PAGAMENTO",
  "side-cart-shopping-listing-20":"Listando os&nbsp;<b>20 primeiros</b>&nbsp;produtos da&nbsp;",
  "side-cart-shopping-listing-20-cart":"cesta",
  "side-cart-shopping-enter-coupon-button":"Inserir cupom",  
  "side-cart-shopping-discount":"Descontos",    
  "side-cart-shopping-interest-10x":"Em até 10x de", 

  /* Smart Suggestions */
  "smart-suggestions-search":"Busca",  
  "smart-suggestions-suggested":"sugerida",   
  "smart-suggestions-for-google":"pelo Google", 

  /* Miscellaneous */
  "form-submit-search-correctly":"Preencha a busca corretamente",  
  "button-cart-warn-me":"Avise-me",  
  "button-cart-warn-me-when-available":"quando estiver disponível.", 
  "show-for-cash-payments-text":"Para pagamentos à vista ganhe", 
  "show-for-cash-payments-discount-text":"% de desconto",
  "show-discount-price":"Valor com desconto",
  "notify-when-available":"Avise-me quando estiver disponível",  
  "cart-on-page-go-to-shopping-cart":"Ir para o carrinho",   
  "get-shipping-insert-zip-code":"Informe o CEP", 
  "get-shipping-insert-zip-code-free-shipping":"FRETE GRÁTIS", 
  "process-xml-cep-shipping":"Frete:", 
  "product-has-been-removed-from-cart":"O produto foi removido do carrinho pois não temos mais em estoque", 
  "quantity-changed-quantity-stock":"A quantidade foi alterada para a quantidade máxima em estoque disponível nesse momento:", 
  "unfortunately-not-have":"Infelizmente não temos", 
  "unfortunately-not-have-units-stock":"unidades em estoque",     
  "change-qty-product-removed":"Produto removido",  
  "change-qty-amount-changed":"Quantidade alterada", 
  "change-qty-cart-product-removed":"Produto removido",

  /* Buy Together */
  "details-buy-together-price":"Preço",
  "details-buy-together-price-was":"de",
  "details-buy-together-price-now":"Por",
  "details-buy-together-save":"Economize",

  /* Grid */
  "grid-text-select-options-below":"Selecione as opções abaixo",
  "grid-add-to-cart-button":"Comprar",
  "grid-ready-button":"Pronto!", 
  "grid-contact-us-button":"Consulte-nos",   
  "grid-sold-out-button":"Esgotado",    
  "grid-choose-options-above-button":"Escolha opções acima",   
  "grid-select-text":"Selecione", 
  "grid-select-options-wishlist":"Selecione as opções acima para inserir na lista de desejos.",  
  "grid-select-payments-win":"Para pagamentos à vista ganhe", 
  "grid-select-payments-win-discount":"% de desconto", 
  "grid-select-payments-win-discount-value":"Valor com desconto", 
  "grid-select-price-on-request":"Preço sob consulta",
  "grid-select-products-missing-descriptors":"Existe um ou mais produtos com descritores ausentes!", 
  "grid-quantity-stock":"Quantidade em Estoque",    
  "grid-quantity-requested-equal-greater":"A quantidade solicitada deve ser igual ou maior que 1.",
  "grid-stock-higher-available":"Estoque solicitado maior que o disponível.",   
  "grid-stock-available-now":"Estoque disponível no momento", 
  "grid-select-available-product":"Selecione um produto disponível primeiro.", 
  "grid-select-product-first":"Selecione primeiro as opções do produto",

  /* Calculate Shopping cart */ 
  "cart-update-text":"Atualizar",
  "cart-zip-code":"Calcular Frete",

  /* Autosuggest */
  "auto-suggest-suggested-searches":"Buscas sugeridas"

}