/* English (en-us) resource file */

var oResources={
  /* Categories - categorias.ehc */
  "cat-more-popular":"More Popular",
  "cat-more-brand-a-to-z":"Brand: A to Z",
  "cat-more-brand-z-to-a":"Brand: Z to A",
  "cat-more-random":"Random",

  /* Header */
  "header-cat-home":"Home",
  "header-cat-sales":"Sales",
  "header-cat-releases":"Releases",
  "header-cat-cart":"Cart",
  "header-cat-my-orders":"My orders",
  "header-cat-my-shopping-list":"Shopping List",
  "header-cat-my-wishlist":"Wishlist",
  "header-cat-register":"Register",
  "header-cat-newsletter":"Newsletter",
  "header-cat-contact-us":"Contact us",
  "header-autosuggest-input":"Search products",
  "header-cat-menu-close":"Close",  
  "header-mainbar-container-search-icon":"Search",    
  "header-cat-search-close":"Close",   
  "header-voice-search-mglass":"Search", 

  /* Home */
  "home-title-sales":"Products on Sale",
  "home-title-special-offers":"Products with special OFFERS!",
  "home-title-special-offers-text":"The best products with the best discounts!",
  "home-title-special-offers-buy-now":"BUY NOW",
  "home-title-last-releases":"Last Releases",
  "home-title-last-awesome-releases":"AWESOME Releases!",
  "home-title-last-awesome-releases-text":"The latest releases! Products with the best prices!",
  "home-title-last-awesome-releases-buy-now":"BUY NOW",
  "home-title-featured-products":"Featured Products",
  "home-section-payment":"See our payment methods",
  "home-section-security":"See our Security badges",
  "home-section-delivery":"Get to know our Fast Shipping",
  "home-section-contact-us":"Any questions? Contact us",  
  "price-in-cash":"in cash",     
  "home-banner-slideshow-sales":"Products on Sale",  
  "home-banner-slideshow-releases":"Last Releases",
  "home-banner-1-slideshow-title":"Amazing offers!",
  "home-banner-1-slideshow-subtitle":"Products with the best discounts!", 
  "home-banner-1-slideshow-button":"BUY NOW",  
  "home-banner-2-slideshow-title":"New Releases!",
  "home-banner-2-slideshow-subtitle":"Products with the best prices!",    
  "home-banner-2-slideshow-button":"BUY NOW", 

  /* Featured Products */
  "featured-products-title":"Featured Products",

  /* Footer */
  "footer-section-title-product":"Products",
  "footer-section-title-home":"Home",
  "footer-section-title-sales":"Sales",
  "footer-section-title-releases":"Releases",
  "footer-section-title-highlights":"Highlights",
  "footer-section-title-search":"Detailed Search",  
  "footer-section-title-my-account":"My account",
  "footer-section-title-shopping-cart":"Shopping cart",
  "footer-section-title-my-orders":"My orders",
  "footer-section-title-register":"Register",
  "footer-section-title-login":"Login",
  "footer-section-title-recommend-us":"Recommend us",
  "footer-section-title-newsletter":"Newsletter",
  "footer-section-title-information":"Information",
  "footer-section-title-help-center":"Help center",
  "footer-section-title-news":"News",
  "footer-section-title-delivery":"Delivery",
  "footer-section-title-security":"Security",
  "footer-section-title-contact-us":"Contact us",
  "footer-section-newsletter-text":"Sign up to receive offers and discounts!",
  "footer-section-newsletter-text-input":"Enter email address",
  "footer-section-title-payment":"Payment",
  "footer-section-powered-by":"Powered by <strong>ehcommerce</strong>",
  "footer-cnpj":" ",
  "footer-newsletter-submit-button":"Submit Newsletter",

  /* Footer - History */
  "footer-history-title":"Your recently viewed items",

  /* Product List */
  "list-filters-title":"Filters",
  "list-price-no-interest":"no interest",
  "list-price-was":"Was",
  "list-price-now":"Now",
  "list-price-call-us":"CALL US",  
  "list-filters-close":"Close", 
  "topic-query-product-cod":"topic=Query%20about%20product%20(Cod%20",
  "list-sold-out":"Sold out",

  /* Product List - Sort by */
  "list-sort-by-title":"Sort By:",
  "list-sort-by-title-select":"Select",
  "list-sort-by-title-default":"Default",
  "list-sort-by-title-releases":"Releases",
  "list-sort-by-title-highlights":"Highlights",
  "list-sort-by-title-cat-names":"Category Names",
  "list-sort-by-title-product-names":"Product Names",
  "list-sort-by-title-reviews":"Customer Reviews",
  "list-sort-by-title-price-low":"Price: Low to High",
  "list-sort-by-title-price-high":"Price: High to Low",

  /* Product Details */
  "details-departments-title":"Departments:",
  "details-description-title":"Description",
  "details-reviews-title":"Reviews",
  "details-zip-code-title":"See the shipping value",
  "details-zip-code-qty":"Qty.",
  "details-zip-code-simulation-brazil":"Simulation only for brazil",
  "details-buy-together-checkbox":"Select",
  "details-buy-together-title":"Buy Together",
  "details-buy-together-add-to-cart-button":"Add to Cart",
  "details-buy-together-price":"Price",
  "details-buy-together-price-was":"was",
  "details-buy-together-price-now":"Now",
  "details-buy-together-save":"Save",
  "details-price-no-interest":"No interest",
  "details-price-no-interest-in":"in",
  "details-price-save":"Save",
  "details-add-to-wishlist-off":"Add to Wishlist",
  "details-add-to-wishlist-on":"Added on to WishList",

  /* Shopping List */
  "shopping-list-title":"My Shopping list",
  "shopping-list-one-product-line":"Enter one product per line.",
  "shopping-list-quick-instructions":"Quick instructions:",
  "shopping-list-enter-one-product-line":"Enter one product per line",
  "shopping-list-press-enter-text":"Press <span class='strColor'>ENTER</span> after entering each product. If you prefer, paste a list of products with one product per line.",
  "shopping-list-find-products":"Find products",
  "shopping-list-after-typing-all-products":"After typing all the products in the list, click the <span class='strColor'> SEARCH PRODUCTS </span> button.",
  "shopping-list-check-results":"Check results",
  "shopping-list-besides-each-product":"Beside each product, you have the options:",
  "shopping-list-search-products":"Search products",
  "shopping-list-mark-purchased":"Mark as purchased",
  "shopping-list-delete-list":"Delete from list",
  "shopping-list-add-cart":"Add to cart",
  "shopping-list-click-each-item-desired-product":"Click each item in the list and select the desired product. Then just click <span class='strColor'> BUY </span>.",
  "shopping-list-change-list":"Change list",
  "shopping-list-restart":"Restart",

  /* Product not find */
  "product-not-find-title":"No products found in this search",
  "product-not-find-tips-search":"Tips for your search:",
  "product-not-find-check-errors":"- Check for typing errors",
  "product-not-find-single-word":"- Try to use a single word",
  "product-not-find-desired-term":"- Try to use synonyms for the desired term",
  "product-not-find-click-here":"Click here",
  "product-not-find-click-here-text":"for a new search.",
  "product-not-find-click-here-sales-btn":"sales",
  
  /* Error 404 */
  "error-404-title":"Error 404",
  "error-404-text":"Sorry, page not found.",

  /* Cart */
  "cart-zip-code-title":"Enter Zip Code to calculate shipping value",
  "cart-zip-code-button":"Calculate Shipping",
  "cart-enter-coupon-button":"Apply Coupon",
  "cart-zip-code-to-calculate":"to calculate",
  "cart-zip-code-shipping-title":"Shipping",

  /* Checkout */
  "checkout-steps-identification":"Identification",
  "checkout-steps-payment":"Payment",
  "checkout-steps-confirmation":"Confirmation",
  "checkout-enter-coupon-title":"Enter your coupon (optional)",
  "checkout-enter-coupon-button":"Apply Coupon",
  "checkout-enter-invalid-coupon":"Invalid coupon",
  "checkout-enter-discount-coupon-text":"Would you like to enter the code for a discount coupon?",
  "checkout-enter-discount-coupon-redirected-text":"If you have a discount coupon you will be redirected to the page where you can enter this coupon to get the discount.",
  "checkout-steps-payment-title":"Payment",
  "checkout-steps-payment-text":"The payment options will be displayed after the step of choosing the shipping.",

  /* Order Confirmation */
  "order-confirmation-payment":"Payment",
  "order-confirmation-payment-data":"Payment data",
  "order-confirmation-payment-information":"Order Information:",

  /* Side Cart */
  "side-cart-shopping-cart-title":"CART",
  "side-cart-shopping-item":"item",
  "side-cart-shopping-items":"items",
  "side-cart-shopping-empty":"Your shopping cart is empty",
  "side-cart-shopping-zip-code":"Zip Code",
  "side-cart-shopping-zip-code-to-calculate":"to calculate",
  "side-cart-shopping-zip-code-invalid":"Invalid",
  "side-cart-shopping-zip-code-button":"Calculate",
  "side-cart-shopping-zip-code-total-pay":"Total to pay",
  "side-cart-shopping-gift":"Gift wrapping",
  "side-cart-shopping-total-itens":"Total Items",
  "side-cart-shopping-proceed-checkout":"PROCEED TO CHECKOUT",
  "side-cart-shopping-listing-20":"Listing the &nbsp;<b>first 20</b>&nbsp;products of the&nbsp;",
  "side-cart-shopping-listing-20-cart":"cart",
  "side-cart-shopping-enter-coupon-button":"Apply coupon",  
  "side-cart-shopping-discount":"Discount",    
  "side-cart-shopping-interest-10x":"Up to 10x", 

  /* Smart Suggestions */
  "smart-suggestions-search":"Search",  
  "smart-suggestions-suggested":"suggested",   
  "smart-suggestions-for-google":"for Google", 

  /* Miscellaneous */
  "form-submit-search-correctly":"Fill in the search correctly",  
  "button-cart-warn-me":"Warn me",  
  "button-cart-warn-me-when-available":"when available.", 
  "show-for-cash-payments-text":"For cash payments win", 
  "show-for-cash-payments-discount-text":"% discount",
  "show-discount-price":"Discount price",
  "notify-when-available":"Notify me when available",  
  "cart-on-page-go-to-shopping-cart":"Go to shopping cart",   
  "get-shipping-insert-zip-code":"Insert Zip Code", 
  "get-shipping-insert-zip-code-free-shipping":"FREE SHIPPING", 
  "process-xml-cep-shipping":"Shipping:", 
  "product-has-been-removed-from-cart":"Product has been removed from cart since we no longer have stock", 
  "quantity-changed-quantity-stock":"The quantity has been changed to the maximum quantity in stock available at the moment:", 
  "unfortunately-not-have":"Unfortunately we do not have", 
  "unfortunately-not-have-units-stock":"units in stock",     
  "change-qty-product-removed":"Product removed",
  "change-qty-amount-changed":"Amount changed",
  "change-qty-cart-product-removed":"Product removed",

  /* Buy Together */
  "details-buy-together-price":"Price",
  "details-buy-together-price-was":"was",
  "details-buy-together-price-now":"Now",
  "details-buy-together-save":"Save",

  /* Grid */
  "grid-text-select-options-below":"Select the options below",
  "grid-add-to-cart-button":"Add to Cart",
  "grid-ready-button":"Added!", 
  "grid-contact-us-button":"Contact us",   
  "grid-sold-out-button":"Sold out",    
  "grid-choose-options-above-button":"Choose the options",   
  "grid-select-text":"Select", 
  "grid-select-options-wishlist":"Select the above options to enter in the wishlist.",  
  "grid-select-payments-win":"For cash payments win", 
  "grid-select-payments-win-discount":"% discount", 
  "grid-select-payments-win-discount-value":"Discount Value", 
  "grid-select-price-on-request":"Price on request",
  "grid-select-products-missing-descriptors":"There are one or more products with missing descriptors!", 
  "grid-quantity-stock":"Quantity in stock",    
  "grid-quantity-requested-equal-greater":"The quantity requested must be equal to or greater than 1.",
  "grid-stock-higher-available":"Stock requested higher than available.",   
  "grid-stock-available-now":"Stock available now", 
  "grid-select-available-product":"Please select an available product first.", 
  "grid-select-product-first":"Please select product options first",

  /* Calculate Shopping cart */ 
  "cart-update-text":"Update",
  "cart-zip-code":"Calculate Shipping",

  /* Autosuggest */
  "auto-suggest-suggested-searches":"Suggested Searches"

}